/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Options1SConfigFrame.java
 *
 * Created on 30.04.2010, 10:13:33
 */

package Interface;

/**
 *
 * @author support
 */
public class Options1SConfigFrame extends javax.swing.JFrame {

    /** Creates new form Options1SConfigFrame */
    public Options1SConfigFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRepair = new javax.swing.ButtonGroup();
        buttonGroupUnresolved = new javax.swing.ButtonGroup();
        jCheckBoxRepair = new javax.swing.JCheckBox();
        jRadioButtonCheckAndRepair = new javax.swing.JRadioButton();
        jRadioButtonCheck = new javax.swing.JRadioButton();
        jCheckBoxPhysicalIntegrity = new javax.swing.JCheckBox();
        jCheckBoxReindex = new javax.swing.JCheckBox();
        jCheckBoxLogicalIntegrity = new javax.swing.JCheckBox();
        jCheckBoxRecalcSec = new javax.swing.JCheckBox();
        jCheckBoxRecalcTotals = new javax.swing.JCheckBox();
        jCheckBoxPackTab = new javax.swing.JCheckBox();
        jCheckBoxSkipUnresolved = new javax.swing.JCheckBox();
        jRadioButtonCreatedForUnresolved = new javax.swing.JRadioButton();
        jRadioButtonClearForUnresolved = new javax.swing.JRadioButton();
        jCheckBoxReconstruct = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jCheckBoxRepair.setText("Выполнять Тестирование и Исправление ИБ");
        jCheckBoxRepair.setNextFocusableComponent(jRadioButtonCheckAndRepair);
        jCheckBoxRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxRepairActionPerformed(evt);
            }
        });

        buttonGroupRepair.add(jRadioButtonCheckAndRepair);
        jRadioButtonCheckAndRepair.setSelected(true);
        jRadioButtonCheckAndRepair.setText("Тестирование и Исправление");
        jRadioButtonCheckAndRepair.setEnabled(false);
        jRadioButtonCheckAndRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCheckAndRepairActionPerformed(evt);
            }
        });

        buttonGroupRepair.add(jRadioButtonCheck);
        jRadioButtonCheck.setText("Только Тестирование");
        jRadioButtonCheck.setEnabled(false);
        jRadioButtonCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCheckActionPerformed(evt);
            }
        });

        jCheckBoxPhysicalIntegrity.setText("Проверка физической целостности");
        jCheckBoxPhysicalIntegrity.setEnabled(false);

        jCheckBoxReindex.setText("Реиндексация");
        jCheckBoxReindex.setEnabled(false);

        jCheckBoxLogicalIntegrity.setText("Проверка логической целостности");
        jCheckBoxLogicalIntegrity.setEnabled(false);

        jCheckBoxRecalcSec.setText("Пересчет служебных данных");
        jCheckBoxRecalcSec.setEnabled(false);

        jCheckBoxRecalcTotals.setText("Пересчет итогов");
        jCheckBoxRecalcTotals.setEnabled(false);

        jCheckBoxPackTab.setText("Упаковка таблицы");
        jCheckBoxPackTab.setEnabled(false);

        jCheckBoxSkipUnresolved.setText("Исправлять неразрешенные ссылки");
        jCheckBoxSkipUnresolved.setEnabled(false);

        buttonGroupUnresolved.add(jRadioButtonCreatedForUnresolved);
        jRadioButtonCreatedForUnresolved.setSelected(true);
        jRadioButtonCreatedForUnresolved.setText("Создавать объекты");
        jRadioButtonCreatedForUnresolved.setEnabled(false);

        buttonGroupUnresolved.add(jRadioButtonClearForUnresolved);
        jRadioButtonClearForUnresolved.setText("Очищать ссылки");
        jRadioButtonClearForUnresolved.setEnabled(false);

        jCheckBoxReconstruct.setText("Реконструкция ИБ");
        jCheckBoxReconstruct.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonCheckAndRepair)
                            .addComponent(jRadioButtonCheck)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxReindex)
                                    .addComponent(jCheckBoxPhysicalIntegrity)
                                    .addComponent(jCheckBoxLogicalIntegrity)
                                    .addComponent(jCheckBoxRecalcSec)
                                    .addComponent(jCheckBoxRecalcTotals)
                                    .addComponent(jCheckBoxPackTab)
                                    .addComponent(jCheckBoxSkipUnresolved)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButtonClearForUnresolved)
                                            .addComponent(jRadioButtonCreatedForUnresolved)))
                                    .addComponent(jCheckBoxReconstruct)))))
                    .addComponent(jCheckBoxRepair))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxRepair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCheckAndRepair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxPhysicalIntegrity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxReindex)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxLogicalIntegrity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxRecalcSec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxRecalcTotals)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxPackTab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxSkipUnresolved)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCreatedForUnresolved)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonClearForUnresolved)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxReconstruct)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxRepairActionPerformed
        if (jCheckBoxRepair.isSelected())
        {
            jCheckBoxLogicalIntegrity.setEnabled(true);
            jCheckBoxPackTab.setEnabled(true);
            jCheckBoxPhysicalIntegrity.setEnabled(true);
            jCheckBoxRecalcSec.setEnabled(true);
            jCheckBoxRecalcTotals.setEnabled(true);
            jCheckBoxReindex.setEnabled(true);
            jRadioButtonCheckAndRepair.setEnabled(true);
            jRadioButtonCheck.setEnabled(true);
            jRadioButtonClearForUnresolved.setEnabled(true);
            jRadioButtonCreatedForUnresolved.setEnabled(true);
            if (jRadioButtonCheck.isSelected())
            {
                jCheckBoxSkipUnresolved.setEnabled(false);
                jRadioButtonClearForUnresolved.setEnabled(false);
                jRadioButtonCreatedForUnresolved.setEnabled(false);
                jCheckBoxReconstruct.setEnabled(false);
            }
            else
            {
                jCheckBoxSkipUnresolved.setEnabled(true);
                jRadioButtonClearForUnresolved.setEnabled(true);
                jRadioButtonCreatedForUnresolved.setEnabled(true);
                jCheckBoxReconstruct.setEnabled(true);
            }
        }
        else
        {
            jCheckBoxLogicalIntegrity.setEnabled(false);
            jCheckBoxPackTab.setEnabled(false);
            jCheckBoxPhysicalIntegrity.setEnabled(false);
            jCheckBoxRecalcSec.setEnabled(false);
            jCheckBoxRecalcTotals.setEnabled(false);
            jCheckBoxReconstruct.setEnabled(false);
            jCheckBoxReindex.setEnabled(false);
            jCheckBoxSkipUnresolved.setEnabled(false);
            jRadioButtonCheckAndRepair.setEnabled(false);
            jRadioButtonCheck.setEnabled(false);
            jRadioButtonClearForUnresolved.setEnabled(false);
            jRadioButtonCreatedForUnresolved.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxRepairActionPerformed

    private void jRadioButtonCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCheckActionPerformed
        if (jRadioButtonCheck.isSelected())
        {
            jCheckBoxSkipUnresolved.setEnabled(false);
            jRadioButtonCreatedForUnresolved.setEnabled(false);
            jRadioButtonClearForUnresolved.setEnabled(false);
            jCheckBoxReconstruct.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButtonCheckActionPerformed

    private void jRadioButtonCheckAndRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCheckAndRepairActionPerformed
        if (jRadioButtonCheckAndRepair.isSelected())
        {
            jCheckBoxSkipUnresolved.setEnabled(true);
            jRadioButtonCreatedForUnresolved.setEnabled(true);
            jRadioButtonClearForUnresolved.setEnabled(true);
            jCheckBoxReconstruct.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonCheckAndRepairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupRepair;
    private javax.swing.ButtonGroup buttonGroupUnresolved;
    private javax.swing.JCheckBox jCheckBoxLogicalIntegrity;
    private javax.swing.JCheckBox jCheckBoxPackTab;
    private javax.swing.JCheckBox jCheckBoxPhysicalIntegrity;
    private javax.swing.JCheckBox jCheckBoxRecalcSec;
    private javax.swing.JCheckBox jCheckBoxRecalcTotals;
    private javax.swing.JCheckBox jCheckBoxReconstruct;
    private javax.swing.JCheckBox jCheckBoxReindex;
    private javax.swing.JCheckBox jCheckBoxRepair;
    private javax.swing.JCheckBox jCheckBoxSkipUnresolved;
    private javax.swing.JRadioButton jRadioButtonCheck;
    private javax.swing.JRadioButton jRadioButtonCheckAndRepair;
    private javax.swing.JRadioButton jRadioButtonClearForUnresolved;
    private javax.swing.JRadioButton jRadioButtonCreatedForUnresolved;
    // End of variables declaration//GEN-END:variables

}
